<?xml version="1.0"?>

<robot name="scout_v2_tracked" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />

    <!-- 属性封装 -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Robot dimensions (m) -->
    <xacro:property name="base_x_size" value="1.15" />
    <xacro:property name="base_y_size" value="0.46" />
    <xacro:property name="base_z_size" value="0.515" />

    <xacro:property name="wheelbase" value="0.498" />
    <xacro:property name="track" value="${base_y_size}" />   <!-- track————车轮间距 -->
    <xacro:property name="wheel_vertical_offset" value="-0.0929" />

    <xacro:property name="wheel_length" value="1.1653e-01" />
    <xacro:property name="wheel_radius" value="1.6459e-01" />

    <!-- Tracked visual envelope (no collision; collision still comes from wheels). -->
    <xacro:property name="track_visual_length" value="0.85" />
    <xacro:property name="track_visual_width" value="0.12" />
    <xacro:property name="track_visual_height" value="0.24" />

    <xacro:arg name="gpu" default="true"/>
    <xacro:property name="gpu" value="$(arg gpu)" />
    <xacro:arg name="organize_cloud" default="true"/>
    <xacro:property name="organize_cloud" value="$(arg organize_cloud)" />
    <xacro:arg name="lidar_hz" default="10"/>
    <xacro:arg name="lidar_samples" default="440"/>
    <xacro:arg name="use_skid_steer" default="false"/>
    <xacro:arg name="use_planar_move" default="true"/>

    <material name="black">
        <color rgba="0.05 0.05 0.05 1.0" />
    </material>

    <!-- 底盘的轮子 -->
    <xacro:include filename="$(find scout_gazebo)/urdf/scout_wheel_type1.xacro" />
    <xacro:include filename="$(find scout_gazebo)/urdf/scout_wheel_type2.xacro" />
    <xacro:include filename="$(find scout_gazebo)/urdf/inertial.xacro" />

    <!-- VLP16 激光雷达 -->
    <xacro:include filename="$(find scout_gazebo)/urdf/laser_support.xacro" />
    <xacro:property name="lidar_x" value="${support_x_size}" />
    <xacro:property name="lidar_z" value="${support_z_size + support_length/2}" />
    <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
    <xacro:VLP-16 parent="support" name="velodyne" topic="/velodyne_points" organize_cloud="${organize_cloud}" hz="$(arg lidar_hz)" samples="$(arg lidar_samples)" gpu="${gpu}">
          <origin xyz="0 0 ${support_length/2}" rpy="0 0 0" />
    </xacro:VLP-16>

    <!-- IMU 模块 -->
    <xacro:include filename="$(find scout_gazebo)/urdf/imu.xacro"/>
    <xacro:imu sensor_name="imu" parent_link="base_link">
    <origin rpy="0 0 0" xyz="${lidar_x} 0 ${lidar_z - 0.10}"/>
    </xacro:imu>

    <!-- 机器人导航控制模块 -->
    <xacro:include filename="$(find scout_gazebo)/urdf/move.xacro" />

    <!-- Base link  底盘 -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_gazebo/meshes/base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.0008" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
    </link>

    <link name="base_footprint"/>
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${-(wheel_radius - wheel_vertical_offset)}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

    <link name="inertial_link">
        <inertial>
            <mass value="40" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- 增强“履带接触长度”的近似：增加中间惰轮（不参与驱动）。 -->
    <xacro:scout_wheel_type1 wheel_prefix="mid_right">
        <origin xyz="0 ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:scout_wheel_type1>
    <xacro:scout_wheel_type2 wheel_prefix="mid_left">
        <origin xyz="0 ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:scout_wheel_type2>

    <!-- 驱动轮（SkidSteerDrive 使用 4 轮关节：front/rear）。 -->
    <xacro:scout_wheel_type1 wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:scout_wheel_type1>
    <xacro:scout_wheel_type2 wheel_prefix="front_left">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:scout_wheel_type2>
    <xacro:scout_wheel_type1 wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:scout_wheel_type1>
    <xacro:scout_wheel_type2 wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:scout_wheel_type2>

    <!-- 履带外观（仅 visual，无 collision）。 -->
    <link name="left_track_visual_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${track_visual_length} ${track_visual_width} ${track_visual_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>
    <joint name="left_track_visual_joint" type="fixed">
        <origin xyz="0 ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="left_track_visual_link" />
    </joint>

    <link name="right_track_visual_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${track_visual_length} ${track_visual_width} ${track_visual_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>
    <joint name="right_track_visual_joint" type="fixed">
        <origin xyz="0 ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="right_track_visual_link" />
    </joint>

    <!-- Hide wheel meshes in Gazebo (keep collisions for dynamics). -->
    <gazebo reference="front_left_wheel_link"><transparency>1.0</transparency></gazebo>
    <gazebo reference="front_right_wheel_link"><transparency>1.0</transparency></gazebo>
    <gazebo reference="rear_left_wheel_link"><transparency>1.0</transparency></gazebo>
    <gazebo reference="rear_right_wheel_link"><transparency>1.0</transparency></gazebo>
    <gazebo reference="mid_left_wheel_link"><transparency>1.0</transparency></gazebo>
    <gazebo reference="mid_right_wheel_link"><transparency>1.0</transparency></gazebo>

</robot>

